services:
  server:
    build:
      context: .
      target: final
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/todos?sslmode=disable
    ports:
      - 8080:8080
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - to-do-list:/var/lib/postgresql/data

volumes:
  to-do-list: